# coding: utf-8

"""
    LiveAgent API

    This page contains complete API documentation for LiveAgent software. To display additional info and examples for specific API method, just click on the method name in the list below.<br/><br/>To be able to make API requests you need to generate an API key in your admin panel first. [See this article for detailed info.](https://support.liveagent.com/741982-API-key)<br/><br/>Additional info about more advanced agent, contact or ticket API filters can be found [in this article](https://support.liveagent.com/513528-APIv3-advanced-filter-examples).<br/><br/>If you have any question or doubts regarding this API, please do not hesitate to contact our support team.  # noqa: E501

    OpenAPI spec version: 3.0.0
    Contact: support@qualityunit.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import liveagent_api
from liveagent_api.api.contact_phones_api import ContactPhonesApi  # noqa: E501
from liveagent_api.rest import ApiException


class TestContactPhonesApi(unittest.TestCase):
    """ContactPhonesApi unit test stubs"""

    def setUp(self):
        self.api = liveagent_api.api.contact_phones_api.ContactPhonesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_contact_phone(self):
        """Test case for get_contact_phone

        Get contact phone  # noqa: E501
        """
        pass

    def test_get_contact_phones_list(self):
        """Test case for get_contact_phones_list

        Gets list of contact phones  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
