# coding: utf-8

"""
    LiveAgent API

    LiveAgent API  # noqa: E501

    OpenAPI spec version: 3.0.0
    Contact: support@qualityunit.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import liveagent_api
from liveagent_api.models.payment_processor_type import PaymentProcessorType  # noqa: E501
from liveagent_api.rest import ApiException


class TestPaymentProcessorType(unittest.TestCase):
    """PaymentProcessorType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPaymentProcessorType(self):
        """Test PaymentProcessorType"""
        # FIXME: construct object with mandatory attributes with example values
        # model = liveagent_api.models.payment_processor_type.PaymentProcessorType()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
