# coding: utf-8

"""
    LiveAgent API

    LiveAgent API  # noqa: E501

    OpenAPI spec version: 3.0.0
    Contact: support@qualityunit.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import liveagent_api
from liveagent_api.models.billing_status import BillingStatus  # noqa: E501
from liveagent_api.rest import ApiException


class TestBillingStatus(unittest.TestCase):
    """BillingStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBillingStatus(self):
        """Test BillingStatus"""
        # FIXME: construct object with mandatory attributes with example values
        # model = liveagent_api.models.billing_status.BillingStatus()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
