# coding: utf-8

"""
    LiveAgent API

    LiveAgent API  # noqa: E501

    OpenAPI spec version: 3.0.0
    Contact: support@qualityunit.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import liveagent_api
from liveagent_api.api.companies_api import CompaniesApi  # noqa: E501
from liveagent_api.rest import ApiException


class TestCompaniesApi(unittest.TestCase):
    """CompaniesApi unit test stubs"""

    def setUp(self):
        self.api = liveagent_api.api.companies_api.CompaniesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_company(self):
        """Test case for create_company

        Create new company  # noqa: E501
        """
        pass

    def test_delete_company(self):
        """Test case for delete_company

        Delete company  # noqa: E501
        """
        pass

    def test_get_companies_list(self):
        """Test case for get_companies_list

        Gets list of companies  # noqa: E501
        """
        pass

    def test_get_specific_company(self):
        """Test case for get_specific_company

        Get company by specific id  # noqa: E501
        """
        pass

    def test_update_company(self):
        """Test case for update_company

        Update company  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
