# coding: utf-8

"""
    LiveAgent API

    This page contains complete API documentation for LiveAgent software. To display additional info and examples for specific API method, just click on the method name in the list below.<br/><br/>To be able to make API requests you need to generate an API key in your admin panel first. [See this article for detailed info.](https://support.ladesk.com/741982-API-key)<br/><br/>Additional info about more advanced agent, contact or ticket API filters can be found [in this article](https://support.ladesk.com/513528-APIv3-advanced-filter-examples).<br/><br/>If you have any question or doubts regarding this API, please do not hesitate to contact our support team.  # noqa: E501

    OpenAPI spec version: 3.0.0
    Contact: support@qualityunit.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import liveagent_api
from liveagent_api.api.slack_api import SlackApi  # noqa: E501
from liveagent_api.rest import ApiException


class TestSlackApi(unittest.TestCase):
    """SlackApi unit test stubs"""

    def setUp(self):
        self.api = liveagent_api.api.slack_api.SlackApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_slack_conversation_id_get(self):
        """Test case for slack_conversation_id_get

        Gets info about Slack workspace channel  # noqa: E501
        """
        pass

    def test_slack_conversations_get(self):
        """Test case for slack_conversations_get

        Gets Slack workspace channels  # noqa: E501
        """
        pass

    def test_slack_template_id_get(self):
        """Test case for slack_template_id_get

        Get Slack template  # noqa: E501
        """
        pass

    def test_slack_template_id_put(self):
        """Test case for slack_template_id_put

        Save Slack template  # noqa: E501
        """
        pass

    def test_slack_templates_get(self):
        """Test case for slack_templates_get

        Gets Slack notification templates  # noqa: E501
        """
        pass

    def test_slack_user_id_get(self):
        """Test case for slack_user_id_get

        Gets info about Slack user  # noqa: E501
        """
        pass

    def test_slack_users_get(self):
        """Test case for slack_users_get

        Gets Slack users in workspace  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
