# coding: utf-8

"""
    LiveAgent API

    LiveAgent API  # noqa: E501

    OpenAPI spec version: 3.0.0
    Contact: support@qualityunit.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import liveagent_api
from liveagent_api.api.messages_api import MessagesApi  # noqa: E501
from liveagent_api.rest import ApiException


class TestMessagesApi(unittest.TestCase):
    """MessagesApi unit test stubs"""

    def setUp(self):
        self.api = liveagent_api.api.messages_api.MessagesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_message(self):
        """Test case for get_message

        Get message  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
