# coding: utf-8

"""
    LiveAgent API

    LiveAgent API  # noqa: E501

    OpenAPI spec version: 3.0.0
    Contact: support@qualityunit.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import liveagent_api
from liveagent_api.models.ivr_fetch import IvrFetch  # noqa: E501
from liveagent_api.rest import ApiException


class TestIvrFetch(unittest.TestCase):
    """IvrFetch unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIvrFetch(self):
        """Test IvrFetch"""
        # FIXME: construct object with mandatory attributes with example values
        # model = liveagent_api.models.ivr_fetch.IvrFetch()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
