# coding: utf-8

"""
    LiveAgent API

    This page contains complete API documentation for LiveAgent software. To display additional info and examples for specific API method, just click on the method name in the list below.<br/><br/>To be able to make API requests you need to generate an API key in your admin panel first. [See this article for detailed info.](https://support.ladesk.com/741982-API-key)<br/><br/>Additional info about more advanced agent, contact or ticket API filters can be found [in this article](https://support.ladesk.com/513528-APIv3-advanced-filter-examples).<br/><br/>If you have any question or doubts regarding this API, please do not hesitate to contact our support team.  # noqa: E501

    OpenAPI spec version: 3.0.0
    Contact: support@qualityunit.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import liveagent_api
from liveagent_api.api.groups_api import GroupsApi  # noqa: E501
from liveagent_api.rest import ApiException


class TestGroupsApi(unittest.TestCase):
    """GroupsApi unit test stubs"""

    def setUp(self):
        self.api = liveagent_api.api.groups_api.GroupsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_group(self):
        """Test case for create_group

        Create contact group  # noqa: E501
        """
        pass

    def test_delete_group(self):
        """Test case for delete_group

        Delete contact group  # noqa: E501
        """
        pass

    def test_get_group_by_id(self):
        """Test case for get_group_by_id

        Get contact group by group id  # noqa: E501
        """
        pass

    def test_get_groups_list(self):
        """Test case for get_groups_list

        Gets list of contact groups  # noqa: E501
        """
        pass

    def test_update_group(self):
        """Test case for update_group

        Update contact group  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
