# coding: utf-8

"""
    LiveAgent API

    LiveAgent API  # noqa: E501

    OpenAPI spec version: 3.0.0
    Contact: support@qualityunit.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import liveagent_api
from liveagent_api.api.extensions_api import ExtensionsApi  # noqa: E501
from liveagent_api.rest import ApiException


class TestExtensionsApi(unittest.TestCase):
    """ExtensionsApi unit test stubs"""

    def setUp(self):
        self.api = liveagent_api.api.extensions_api.ExtensionsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_extension(self):
        """Test case for get_extension

        Gets Extension  # noqa: E501
        """
        pass

    def test_get_extensions_list(self):
        """Test case for get_extensions_list

        Gets list of extensions  # noqa: E501
        """
        pass

    def test_set_extension(self):
        """Test case for set_extension

        Set extension  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
