# coding: utf-8

"""
    LiveAgent API

    LiveAgent API  # noqa: E501

    OpenAPI spec version: 3.0.0
    Contact: support@qualityunit.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import liveagent_api
from liveagent_api.api.departments_api import DepartmentsApi  # noqa: E501
from liveagent_api.rest import ApiException


class TestDepartmentsApi(unittest.TestCase):
    """DepartmentsApi unit test stubs"""

    def setUp(self):
        self.api = liveagent_api.api.departments_api.DepartmentsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_department_list(self):
        """Test case for get_department_list

        Gets list of departments  # noqa: E501
        """
        pass

    def test_get_specific_department(self):
        """Test case for get_specific_department

        Get department by specific id  # noqa: E501
        """
        pass

    def test_if_agent_is_in_department(self):
        """Test case for if_agent_is_in_department

        Is agent is department  # noqa: E501
        """
        pass

    def test_update_department_mail_account(self):
        """Test case for update_department_mail_account

        Update department mail account  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
