# coding: utf-8

"""
Copyright 2016 SmartBear Software

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

    Ref: https://github.com/swagger-api/swagger-codegen
"""

from pprint import pformat
from six import iteritems


class PageVisit(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self):
        """
        PageVisit - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'browser': 'str',
            'date_visit': 'datetime',
            'title': 'str',
            'url': 'str',
            'referrerurl': 'str'
        }

        self.attribute_map = {
            'browser': 'browser',
            'date_visit': 'date_visit',
            'title': 'title',
            'url': 'url',
            'referrerurl': 'referrerurl'
        }

        self._browser = None
        self._date_visit = None
        self._title = None
        self._url = None
        self._referrerurl = None

    @property
    def browser(self):
        """
        Gets the browser of this PageVisit.


        :return: The browser of this PageVisit.
        :rtype: str
        """
        return self._browser

    @browser.setter
    def browser(self, browser):
        """
        Sets the browser of this PageVisit.


        :param browser: The browser of this PageVisit.
        :type: str
        """
        self._browser = browser

    @property
    def date_visit(self):
        """
        Gets the date_visit of this PageVisit.


        :return: The date_visit of this PageVisit.
        :rtype: datetime
        """
        return self._date_visit

    @date_visit.setter
    def date_visit(self, date_visit):
        """
        Sets the date_visit of this PageVisit.


        :param date_visit: The date_visit of this PageVisit.
        :type: datetime
        """
        self._date_visit = date_visit

    @property
    def title(self):
        """
        Gets the title of this PageVisit.


        :return: The title of this PageVisit.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """
        Sets the title of this PageVisit.


        :param title: The title of this PageVisit.
        :type: str
        """
        self._title = title

    @property
    def url(self):
        """
        Gets the url of this PageVisit.


        :return: The url of this PageVisit.
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url):
        """
        Sets the url of this PageVisit.


        :param url: The url of this PageVisit.
        :type: str
        """
        self._url = url

    @property
    def referrerurl(self):
        """
        Gets the referrerurl of this PageVisit.


        :return: The referrerurl of this PageVisit.
        :rtype: str
        """
        return self._referrerurl

    @referrerurl.setter
    def referrerurl(self, referrerurl):
        """
        Sets the referrerurl of this PageVisit.


        :param referrerurl: The referrerurl of this PageVisit.
        :type: str
        """
        self._referrerurl = referrerurl

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other

