# coding: utf-8

"""
Copyright 2016 SmartBear Software

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

    Ref: https://github.com/swagger-api/swagger-codegen
"""

from pprint import pformat
from six import iteritems


class TicketSla(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self):
        """
        TicketSla - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'conversationid': 'str',
            'first_answer': 'datetime',
            'first_assign': 'datetime',
            'first_resolve': 'datetime',
            'next_answer': 'datetime'
        }

        self.attribute_map = {
            'conversationid': 'conversationid',
            'first_answer': 'first_answer',
            'first_assign': 'first_assign',
            'first_resolve': 'first_resolve',
            'next_answer': 'next_answer'
        }

        self._conversationid = None
        self._first_answer = None
        self._first_assign = None
        self._first_resolve = None
        self._next_answer = None

    @property
    def conversationid(self):
        """
        Gets the conversationid of this TicketSla.


        :return: The conversationid of this TicketSla.
        :rtype: str
        """
        return self._conversationid

    @conversationid.setter
    def conversationid(self, conversationid):
        """
        Sets the conversationid of this TicketSla.


        :param conversationid: The conversationid of this TicketSla.
        :type: str
        """
        self._conversationid = conversationid

    @property
    def first_answer(self):
        """
        Gets the first_answer of this TicketSla.


        :return: The first_answer of this TicketSla.
        :rtype: datetime
        """
        return self._first_answer

    @first_answer.setter
    def first_answer(self, first_answer):
        """
        Sets the first_answer of this TicketSla.


        :param first_answer: The first_answer of this TicketSla.
        :type: datetime
        """
        self._first_answer = first_answer

    @property
    def first_assign(self):
        """
        Gets the first_assign of this TicketSla.


        :return: The first_assign of this TicketSla.
        :rtype: datetime
        """
        return self._first_assign

    @first_assign.setter
    def first_assign(self, first_assign):
        """
        Sets the first_assign of this TicketSla.


        :param first_assign: The first_assign of this TicketSla.
        :type: datetime
        """
        self._first_assign = first_assign

    @property
    def first_resolve(self):
        """
        Gets the first_resolve of this TicketSla.


        :return: The first_resolve of this TicketSla.
        :rtype: datetime
        """
        return self._first_resolve

    @first_resolve.setter
    def first_resolve(self, first_resolve):
        """
        Sets the first_resolve of this TicketSla.


        :param first_resolve: The first_resolve of this TicketSla.
        :type: datetime
        """
        self._first_resolve = first_resolve

    @property
    def next_answer(self):
        """
        Gets the next_answer of this TicketSla.


        :return: The next_answer of this TicketSla.
        :rtype: datetime
        """
        return self._next_answer

    @next_answer.setter
    def next_answer(self, next_answer):
        """
        Sets the next_answer of this TicketSla.


        :param next_answer: The next_answer of this TicketSla.
        :type: datetime
        """
        self._next_answer = next_answer

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other

