# coding: utf-8

"""
    LiveAgent API

    LiveAgent API  # noqa: E501

    OpenAPI spec version: 3.0.0
    Contact: support@qualityunit.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class TicketPostpone(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'date_time': 'str',
        'userid': 'str'
    }

    attribute_map = {
        'date_time': 'date_time',
        'userid': 'userid'
    }

    def __init__(self, date_time=None, userid=None):  # noqa: E501
        """TicketPostpone - a model defined in Swagger"""  # noqa: E501

        self._date_time = None
        self._userid = None
        self.discriminator = None

        self.date_time = date_time
        if userid is not None:
            self.userid = userid

    @property
    def date_time(self):
        """Gets the date_time of this TicketPostpone.  # noqa: E501

        - date and time with valid format: YYYY-MM-DD HH:MM:SS  # noqa: E501

        :return: The date_time of this TicketPostpone.  # noqa: E501
        :rtype: str
        """
        return self._date_time

    @date_time.setter
    def date_time(self, date_time):
        """Sets the date_time of this TicketPostpone.

        - date and time with valid format: YYYY-MM-DD HH:MM:SS  # noqa: E501

        :param date_time: The date_time of this TicketPostpone.  # noqa: E501
        :type: str
        """
        if date_time is None:
            raise ValueError("Invalid value for `date_time`, must not be `None`")  # noqa: E501

        self._date_time = date_time

    @property
    def userid(self):
        """Gets the userid of this TicketPostpone.  # noqa: E501


        :return: The userid of this TicketPostpone.  # noqa: E501
        :rtype: str
        """
        return self._userid

    @userid.setter
    def userid(self, userid):
        """Sets the userid of this TicketPostpone.


        :param userid: The userid of this TicketPostpone.  # noqa: E501
        :type: str
        """

        self._userid = userid

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TicketPostpone, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TicketPostpone):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
