from __future__ import absolute_import

# import apis into api package
from .agentphone_api import AgentphoneApi
from .agents_api import AgentsApi
from .api_api import ApiApi
from .bans_api import BansApi
from .billing_api import BillingApi
from .calls_api import CallsApi
from .cannedmessages_api import CannedmessagesApi
from .chats_api import ChatsApi
from .companies_api import CompaniesApi
from .contactphones_api import ContactphonesApi
from .contacts_api import ContactsApi
from .countries_api import CountriesApi
from .custombuttons_api import CustombuttonsApi
from .default_api import DefaultApi
from .departments_api import DepartmentsApi
from .devices_api import DevicesApi
from .extensions_api import ExtensionsApi
from .files_api import FilesApi
from .filters_api import FiltersApi
from .groups_api import GroupsApi
from .hosting_api import HostingApi
from .invoices_api import InvoicesApi
from .mailaccount_api import MailaccountApi
from .messages_api import MessagesApi
from .pagevisits_api import PagevisitsApi
from .phonenumbers_api import PhonenumbersApi
from .phones_api import PhonesApi
from .plans_api import PlansApi
from .predefinedanswers_api import PredefinedanswersApi
from .queue_api import QueueApi
from .settings_api import SettingsApi
from .slas_api import SlasApi
from .subscriptions_api import SubscriptionsApi
from .tags_api import TagsApi
from .tickets_api import TicketsApi
from .token_api import TokenApi
from .user_api import UserApi
from .variations_api import VariationsApi
